name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Backend setup
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # Frontend setup
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Run backend (basic check)
        run: |
          cd backend
          node server.js &
          sleep 5